### ISSUE TITLE
[Feat Request]: ResultAtom

### ISSUE THREAD

**Issue by smiLLe** [ra1028/swiftui-atom-properties#85]
### Checklist

- [X] Reviewed the README and documentation.
- [X] Checked existing issues & PRs to ensure not duplicated.

### Description

Hi,
I just found this lib because I am familiar with riverpod :) So nice to see someone did a "port".

I have an Api class in Swift which for example offers a function like:
```swift
class Api {
  func fetchUser() async -> Result<User, ApiError> { ... }
}
```
But unfortunately I do not completely understand if this is possible using the existing Atoms.
I want to return a Result but much more important is the typed Error.

### Example Use Case

See description

**Comment by ra1028** [comment]
That's possible using TaskAtom.

```swift
struct FetchUserAtom: TaskAtom, Hashable {
    func value(context: Context) async -> Result<User, ApiError> {
        let api = context.watch(ApiAtom())
        return await api.fetchUser()
    }
}

struct UserView: View {
    @Watch(FetchUserAtom())
    var userTask

    var body: some View {
        Suspense(userTask) { result in
            Text(user?.name ?? "Unknown")
            switch result {
            case .success(let user):
                Text(user.name)

            case .failure(let error):
                Text (error.localizedDescription)
            }
        }
    }
}
```

It produces a `Task<Result<User, ApiError>, Never` value but it's impossible to flatten the resulting error type into `Task<User, ApiError>` because it's essentially unsupported in Swift Concurrency.

**Comment by smiLLe** [comment]
Thanks for the fast reply!
I will give it a try :)

**Comment by smiLLe** [comment]
@ra1028  What is the correct way to handle an TaskAtom watching the result of another TaskAtom? 

```swift
struct FetchUserAtom: TaskAtom, Hashable {
    func value(context: Context) async -> Result<User, ApiError> {
        let api = context.watch(ApiAtom())
        return await api.fetchUser()
    }
}

struct OtherAtom: TaskAtom, Hashable {
    func value(context: Context) async -> Result<Other, ApiError> {
        let userResult = context.watch(FetchUserAtom().changes)
        // I want to use await the FetchUserAtom and use User
    }
}
```

**Comment by smiLLe** [comment]
```swift
struct OtherAtom: TaskAtom, Hashable {
    func value(context: Context) async -> Result<Other, ApiError> {
       let result = await context.watch(FetchUserAtom().changes).value
    }
}
```
