### ISSUE TITLE
[Bug]: crash in previews

### ISSUE THREAD

**Issue by joprice** [ra1028/swiftui-atom-properties#90]
### Checklist

- [X] This is not a bug caused by platform.
- [X] Reviewed the README and documentation.
- [X] Checked existing issues & PRs to ensure not duplicated.

### What happened?

Preview crashes when calling `StoreContext.getStore`. It seems that the `AtomRoot` is not configured in the preview, although I am calling it as documented:

```swift
#Preview("PreviewTest"){
   AtomRoot {
      PreviewTest()
    }
}
```

### Expected Behavior

Atoms should be usable in previews

### Reproduction Steps

1. Reference any Atom in a preview

### Swift Version

5.9.2

### Library Version

0.4.2

### Platform

iOS

### Scrrenshot/Video/Gif

Snippet of diagnostic report:
 
<img width="849" alt="Screenshot 2023-12-20 at 3 33 04 PM" src="https://github.com/ra1028/swiftui-atom-properties/assets/2175555/f7a5ece1-60c1-46ea-9e84-d0a8b784ac21">

This is shown if `@ViewContext` or `@Watch` is used. If the context is read directly in the view, the full assertion is shown.

**Comment by ra1028** [comment]
@joprice 

I've tried to replace [this part](https://github.com/ra1028/swiftui-atom-properties/blob/main/Examples/Packages/iOS/Sources/ExampleMovieDB/Screens/MoviesScreen.swift#L98-L106) of the example app with one using #Preview macro and it worked fine.
Please double check if there are any problems with your environment, Xcode version, simulator, PreviewTest view implementation, etc.

<img width="600" alt="Screenshot 2023-12-25 at 18 07 47" src="https://github.com/ra1028/swiftui-atom-properties/assets/7347118/80c75e1d-bdfa-4b73-9880-8f0bf94b7eb4">
